name       : exfat-utils
version    : 1.2.3
release    : 5
source     :
    - https://github.com/relan/exfat/releases/download/v1.2.3/exfat-utils-1.2.3.tar.gz : 80d3b3f21242d60d36a38a4ddb05cb7cc3a7d4eef5793e8314814937b938fcea
license    : GPL-2.0
summary    : exFAT file system utilities
description: |
    exFAT file system utilities
setup      : |
    %configure --disable-static --bindir=/usr/bin --sbindir=/usr/sbin
build      : |
    %make 
install    : |
    %make_install
    install -D -m 00644 dump/dumpexfat.8 %installroot%/usr/share/man/man8/dumpexfat.8
    install -m 00644 fsck/exfatfsck.8 %installroot%/usr/share/man/man8
    install -m 00644 mkfs/mkexfatfs.8 %installroot%/usr/share/man/man8
    install -m 00644 label/exfatlabel.8 %installroot%/usr/share/man/man8
