name       : exfat-utils
version    : 1.2.7
release    : 7
source     :
    - https://github.com/relan/exfat/releases/download/v1.2.7/exfat-utils-1.2.7.tar.gz : 386132d155b92c7d27735483663f2724844cb904ef9ecd83c374cffe831dffe4
license    : GPL-2.0
summary    : exFAT file system utilities
description: |
    exFAT file system utilities
component  : system.utils
setup      : |
    %configure --disable-static --bindir=/usr/bin --sbindir=/usr/sbin
build      : |
    %make 
install    : |
    %make_install
    install -D -m 00644 dump/dumpexfat.8 %installroot%/usr/share/man/man8/dumpexfat.8
    install -m 00644 fsck/exfatfsck.8 %installroot%/usr/share/man/man8
    install -m 00644 mkfs/mkexfatfs.8 %installroot%/usr/share/man/man8
    install -m 00644 label/exfatlabel.8 %installroot%/usr/share/man/man8
