name       : exfat-utils
version    : 1.3.0
release    : 9
source     :
    - https://github.com/relan/exfat/archive/v1.3.0.tar.gz : 689bcb4a639acd2d45e6fa0ff455f7f18edb2421d4f4f42909943775adc0e375
license    : GPL-2.0-or-later
summary    : exFAT file system utilities
description: |
    Full-featured exFAT file system implementation for Unix-like systems. It consists of a FUSE module (fuse-exfat) and a set of utilities (exfat-utils).
component  : system.utils
builddeps  :
    - pkgconfig(fuse)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
    install -D -m00644 */*.8 -t $installdir/usr/share/man/man8
