name       : exfat-utils
version    : 1.2.8
release    : 8
source     :
    - https://github.com/relan/exfat/archive/v1.2.8.tar.gz : 778474bfbcd92e35bba5b88bd7ad3f6400328256636abb9031bfcc1ce15ed887
license    : GPL-2.0
summary    : exFAT file system utilities
description: |
    exFAT file system utilities
component  : system.utils
builddeps  :
    - pkgconfig(fuse)
setup      : |
    %reconfigure --disable-static --bindir=/usr/bin --sbindir=/usr/sbin
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 dump/dumpexfat.8 %installroot%/usr/share/man/man8/dumpexfat.8
    install -m 00644 fsck/exfatfsck.8 %installroot%/usr/share/man/man8
    install -m 00644 mkfs/mkexfatfs.8 %installroot%/usr/share/man/man8
    install -m 00644 label/exfatlabel.8 %installroot%/usr/share/man/man8
