name       : exfat-utils
version    : 1.1.1
release    : 2
source     :
    - https://docs.google.com/uc?export=download&id=0B7CLI-REKbE3UzNtSkRvdHBpdjQ : c64454083961fbad164fa7daef03d7e9247aa978c11395d62a265d48a1d56232
license    : GPL-2.0
summary    : exFAT file system utilities
description: |
    exFAT file system utilities
builddeps  :
    - scons
install    : |
    scons install DESTDIR=%installroot%/usr/bin
    install -Dm444 dump/dumpexfat.8 %installroot%/usr/share/man/man8/dumpexfat.8
    install -m444 fsck/exfatfsck.8 %installroot%/usr/share/man/man8
    install -m444 mkfs/mkexfatfs.8 %installroot%/usr/share/man/man8
    install -m444 label/exfatlabel.8 %installroot%/usr/share/man/man8
